### ISSUE TITLE
[Bug] Settings are not getting saved.

### ISSUE THREAD

**Issue by LucioAmely** [javulticat/NewPipe#15]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/javulticat/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/javulticat/NewPipe/issues) or [closed](https://github.com/javulticat/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/javulticat/NewPipe/blob/sponsorblock/.github/CONTRIBUTING.md).

### Affected version

v0.26.1-2

### Steps to reproduce the bug

Installed your fork, customized my settings. When I force close the app and launch it again it reverts back to default settings.

Tried to use my exported database from polymophicshade's latest version. It reverted back to default settings again after force close.

Subscriptions and saved playlists remain in contact. Only app settings revert back to default.

### Expected behavior

Settings should get saved.

### Actual behavior

Settings revert back to default.

### Affected Android/Custom ROM version

AndroidOne 7.1.2

### Affected device model

Xiaomi Mi A1

**Comment by LucioAmely** [comment]
Now after cleaning app's data settings are getting saved. Might need further inspecting to see what caused it in the beginning.

**Comment by LucioAmely** [comment]
> Thanks for the report! I'm glad you were able to find a simple resolution to the problem.
> 
> Unfortunately, I'm unable to reproduce this issue when I try recreating the chain of events you described. Unless a method to consistently reproduce this issue can be found, there isn't much that can be done to investigate it.
> 
> It also doesn't seem like there is enough information here to rule out the possibility that this may be an upstream issue (i.e., would performing the same steps to migrate from `polymorphicshade`'s `v0.25.2` to upstream's `v0.26.1` also have resulted in the same behavior prior to clearing the cache?). Existence of this issue in upstream would need to be definitively ruled out before it could be investigated here.
> 
> Closing for now as there is nothing actionable that can be done here currently - can reopen if/when the following can be provided:
> 
> * Steps that allow the issue to be consistently reproduced
> * Proof that the issue cannot be reproduced in upstream

Yes I have tested from PolymorphicShade's version to upstream, it did not happened and I have checkmarked the appropriate checkbox in the issue template accordingly. I am still trying to reproduce the steps. Thank you for taking your time. I will inform you if I can find the cause.

**Comment by LucioAmely** [comment]
Is there any way that I can manually access NewPipe's logs like the screen appears when the app crashes other than using the logcat? When I am able to reproduce it would like to send the logs to you as well.

**Comment by javulticat** [comment]
Thanks for confirming your test against upstream.  It's not uncommon for folks to check off items without actually doing what they say (or even reading them 🙃), so I appreciate that.  And I most certainly appreciate your continued interest in investigating this issue!

To answer your question, you should have access to a variety of tools to assist with debugging if you install a debug APK version of the app.  I'd specifically suggest installing [this one](https://github.com/javulticat/NewPipe/actions/runs/7415277293/artifacts/1148791792) (note that the debug APK is compressed into zip archive and will need to be extracted before use).  It was produced by the [CI pipeline](https://github.com/javulticat/NewPipe/actions/runs/7415277293) run on the exact commit (https://github.com/javulticat/NewPipe/commit/6a238e29e2fdb931fa0c9eca3a7c4b591941854b) that was [tagged and released](https://github.com/javulticat/NewPipe/releases/tag/v0.26.1-2) as `v0.26.1-2` (you'll see https://github.com/javulticat/NewPipe/commit/6a238e29e2fdb931fa0c9eca3a7c4b591941854b listed near the top of the Release notes next to the tag name). So, it should be as identical an APK as possible to the one from the`v0.26.1-2` Release, other than the fact that it is a debug APK that has various debugging options enabled and/or exposed (which can be found in the Settings).

Note that debug APKs are known to be less performant, which can cause noticeable performance issues (i.e., "lag") on certain devices (#3). So, just a heads up that you may notice degraded performance compared to running the official release APK, but that's to be expected when using a debug APK.

**Comment by LucioAmely** [comment]
Thank you for the debug APK, I will try my best to reproduce it.
