### ISSUE TITLE
Release v0.26.1

### ISSUE THREAD

**Issue by javulticat** [javulticat/NewPipe#2]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/javulticat/NewPipe/issues) or [closed](https://github.com/javulticat/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/javulticat/NewPipe/blob/sponsorblock/.github/CONTRIBUTING.md).

### Feature description

Pull in `v0.26.1` from upstream and release a `NewPipe x SponsorBlock` version of `v0.26.1`

### Why do you want this feature?

New features and bug fixes since `v0.25.2`

### Why is the feature relevant to this fork?

Changes are already in upstream, but not in fork.

### Additional information

Since https://github.com/polymorphicshade/NewPipe is archived, but multiple users had requested a release containing upstream changes from `v0.26.1` (https://github.com/polymorphicshade/NewPipe/issues/377), it'll have to be done in this new repo.

**Comment by javulticat** [comment]
Completed in https://github.com/javulticat/NewPipe/commit/351c39d569f6a1f32364558815d3e7b230333d14, see https://github.com/javulticat/NewPipe/releases/tag/v0.26.1 for `v0.26.1` APK download.

**Comment by javulticat** [comment]
FYI: An improved `v0.26.1` release (~50% smaller size, more performant, automated build process) is now available here: https://github.com/javulticat/NewPipe/releases/tag/v0.26.1-2

**Comment by Coool** [comment]
@javulticat, version informatiom still showing 0.25.2. Have you forgot update?

**Comment by javulticat** [comment]
@Coool, could you elaborate on where you are seeing this? This is what I see on the "About" screen while using the latest release, [`v0.26.1-2`](https://github.com/javulticat/NewPipe/releases/tag/v0.26.1-2):

![image](https://github.com/javulticat/NewPipe/assets/31746850/7478aa0d-e3b6-4693-af26-ca94ef8a2f7c)

And here is what I see under "App Info" in Android:

![image](https://github.com/javulticat/NewPipe/assets/31746850/db429f2c-4f68-41d9-8e5a-475029bb5c26)

As you can see, both indicate version `0.26.1`.

**Comment by Coool** [comment]
@javulticat, it new app under com.javulticat.newpipe name. I hope what name won't change again as with your first released APK file. Late evening sindrome, I'm sorry for my mistake. I report if I have any issue.

Thanks.
